### ISSUE TITLE
Specifying local-path includes directory structure on upload

### ISSUE THREAD

**Issue by cjboco** [milanmk/actions-file-deployer#10]
If I specify "local-path" as something other that ".", say "./src", it will copy the "src" folder along with the changed file to the remote path.

Example .yml:
-----------------------
remote-path/wp-content/themes/my-theme
local-path ./src

then if I change a file and push, say: sample.php

on upload, I will see:
-----------------------
index.php
about.php
src/
- sample.php

desired effect:
-----------------------
index.php
about.php
sample.php

Not sure if it's a bug or a feature not implemented. But makes it difficult when remote and local directories don't match.

**Comment by milanmk** [comment]
File deployments are usually done on similar local and remote path and this action is built based on those requirements. I don't think this action can handle non matching local and remote path.

**Comment by cjboco** [comment]
Ah.. okay. I just thought I was doing something wrong or perhaps an issue. Thanks!
