### ISSUE TITLE
Action succeeds if lftp errors

### ISSUE THREAD

**Issue by gushogg-blake** [milanmk/actions-file-deployer#14]
The action continues even if the lftp command errors - is this intended? I'm working on a project where we would like the CI job to fail if the lftp command errors out. I think this would achieve it: https://github.com/gushogg-blake/actions-file-deployer/commit/d094460c9d1cb5e2b68afe7492a54265767fc7b7

**Comment by milanmk** [comment]
You can set this `set cmd:fail-exit true` in `ftp-options` input.
