### ISSUE TITLE
Please update the following actions to use Node.js 16: actions/upload-artifact@v2

### ISSUE THREAD

**Issue by chberger** [milanmk/actions-file-deployer#16]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact@v2

**Comment by milanmk** [comment]
upload-artifact version updated in v1.12 https://github.com/milanmk/actions-file-deployer/releases/tag/1.12

**Comment by chberger** [comment]
Thanks
