### ISSUE TITLE
Update @actions/upload-artifact to v4

### ISSUE THREAD

**Issue by IrinaGrigoryan** [milanmk/actions-file-deployer#25]
Hello! Thank you for your work! You've created a great plugin!

Just one thing. 
I have a warning during my GitHub Actions workflow:
_Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/._

Could you please update **@actions/upload-artifact to v4**?

![image](https://github.com/milanmk/actions-file-deployer/assets/39583396/6e05c5cb-b8fc-431f-ab2c-0979f9353cf2)

Thanks!

**Comment by milanmk** [comment]
Fixed in release 1.14

**Comment by IrinaGrigoryan** [comment]
That works! Many thanks!
