### ISSUE TITLE
Exclude directories on full sync example

### ISSUE THREAD

**Issue by titosemi** [milanmk/actions-file-deployer#26]
Hi.

first of all, thanks a lot for the great repo!

I am struggling with the syntax for excluding certain directories with the full sync.
I think that I should be using the **ftp-mirror-options** property. So far I have tried, without success, exclude, --exclude, --exclude-glob, --exclude-glob=.

Thanks a lot in advance for your support!

**Comment by channelaffairs** [comment]
Could you provide examples of the exclude options that you have tried with mirror.

**Comment by milanmk** [comment]
Could you provide examples of the exclude options that you have tried with mirror.

**Comment by titosemi** [comment]
My last try was like this:

```
          ftp-mirror-options: |
            --exclude-glob=.git/* 
            --exclude-glob=.git*/* 
            --exclude-glob=build/* 
            --exclude-glob=data/* 
            --exclude-glob=node_modules/*
```

**Comment by milanmk** [comment]
Try this:

```
ftp-mirror-options: "--exclude-glob=.git/* --exclude-glob=.git*/* --exclude-glob=build/* --exclude-glob=data/* --exclude-glob=node_modules/*"
```

**Comment by titosemi** [comment]
That did the trick.

Thanks a lot for the help!
