### ISSUE TITLE
Can we add SSH key passphrase support?

### ISSUE THREAD

**Issue by theloveofcode** [milanmk/actions-file-deployer#30]
I've tried forking this myself to add it, but have been unsuccessful. Are you able to add support for SSH key passphrase with non-empty passphrases?

**Comment by milanmk** [comment]
Based on the available LFTP options, I don't think this can be automated. This action internally uses `sftp:connect-program` option to connect via SSH but there is no way to automate passing of the SSH Key passphrase.
