### ISSUE TITLE
usr/bin/lftp: Argument list too long

### ISSUE THREAD

**Issue by floriancnx** [milanmk/actions-file-deployer#35]
Hi, i have this use. Please some body, can help me. 

 File created: ~/files_to_delete
  ____________________________________________________________________________________________________
Transfer files
  Protocol: ftp
  Synchronization: delta
  Local path: src
  Remote path: /home/runner/work/xxxxxxxxx/xxxxxxxxx
  Upload files: 6525
  Delete files: 0
  ____________________________________________________________________________________________________
  /home/runner/work/_temp/1873f9b5-963e-4a6a-9944-c7d3d6933d02.sh: line 293: /usr/bin/lftp: Argument list too long
  Error: Process completed with exit code 126.

**Comment by milanmk** [comment]
> Upload files: 6525

Do a full sync first and then use delta sync so that only modified files need to be uploaded.
