### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by Bammede** [milanmk/actions-file-deployer#7]
Alongside SSH with keys (authentication with keys only).
I setup SFTP with users and passwords (no keys). I can login to SFTP by FileZilla with user and password and do not need keys.
```
          remote-host: "${{ secrets.HOST }}"
          remote-port: "${{ secrets.PORT }}"
          remote-user: "${{ secrets.USERNAME }}"
          remote-password: "${{ secrets.PASSWORD }}"
```
Actions shows error: Permission denied (publickey).

**Comment by milanmk** [comment]
It looks like a setup issue on the runner. You can enable "debug" input parameter to help you debug this issue.
